# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-25 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constructo',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaProjeto',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('IdEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twqsystem.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EquipeUsuario',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('IdEquipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twqsystem.Equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Expiration', models.DateTimeField(blank=True, null=True)),
                ('Date_Send', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuncaoUsuario',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Setor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloFormulario',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=200)),
                ('Descricao', models.TextField()),
                ('Date_Created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloFormularioEmpresa',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='twqsystem.Empresa')),
                ('modeloFormulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='twqsystem.ModeloFormulario')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Cliente', models.CharField(max_length=200)),
                ('Status', models.BooleanField()),
                ('Deadline', models.DateTimeField(blank=True, null=True)),
                ('Nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Pergunta', models.TextField()),
                ('Invertido', models.BooleanField()),
                ('IdFormulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='twqsystem.ModeloFormulario')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('IdQuestao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twqsystem.Questao')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=200)),
                ('UserName', models.CharField(max_length=200)),
                ('Senha', models.CharField(max_length=100)),
                ('Funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twqsystem.FuncaoUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioFormulario',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Status_Respondido', models.BooleanField()),
                ('IdFormulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twqsystem.Formulario')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='twqsystem.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Variavel',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=200)),
                ('IdConstructo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='twqsystem.Constructo')),
                ('IdFuncaoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='twqsystem.FuncaoUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='VariavelQuestao',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('IdQuestao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='twqsystem.Questao')),
                ('IdVariavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='twqsystem.Variavel')),
            ],
        ),
        migrations.AddField(
            model_name='resposta',
            name='IdUsuarioFormulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='twqsystem.UsuarioFormulario'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='IdModeloFormulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='twqsystem.ModeloFormulario'),
        ),
        migrations.AddField(
            model_name='equipeusuario',
            name='IdUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twqsystem.Usuario'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='IdProjeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='twqsystem.Projeto'),
        ),
        migrations.AddField(
            model_name='empresaprojeto',
            name='IdProjeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twqsystem.Projeto'),
        ),
        migrations.AddField(
            model_name='constructo',
            name='IdModeloFormulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='twqsystem.ModeloFormulario'),
        ),
    ]
