# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-25 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twqsystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeloformularioempresa',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='modeloformularioempresa',
            name='modeloFormulario',
        ),
        migrations.AddField(
            model_name='modeloformulario',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='twqsystem.Empresa'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ModeloFormularioEmpresa',
        ),
    ]
