# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-18 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twqsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructo',
            name='IdModeloFormulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twqsystem.ModeloFormulario'),
        ),
    ]
